### ISSUE TITLE
Space usage doesn't include files uploaded using the S3 settings

### ISSUE THREAD

**Issue by ReneSmeekes** [storj-thirdparty/vortex#100]
Only files uploaded through the web browser are counted. I've removed those and space usage now shows 0 despite lots of files being there uploaded through the S3 compatibility.

**Comment by super3** [comment]
@ReneSmeekes Files uploaded through s3 settings can take up to 24 hours to appear. We should display a warning somewhere.

**Comment by ReneSmeekes** [comment]
Ahh got it! I figured it was something like that since it's similar on the satellite interface. It hasn't appeared for me yet, but I'll check back in a bit as it's only been about 18 hours.

To be honest I was surprised to see the information appear directly when uploading through the browser. Nice touch!

**Comment by Kalloritis** [comment]
Is there a reason that the S3 uploaded files take so much longer compared to the web uploads? I have 3 Duplicati jobs going and their space/files/bandwidth are not reporting. The one 31GiB web upload reported quite quickly respective to when it finished uploading. Is this because the S3 side of thing has to retroactively fill in space/file count/bandwidth since its a separate gateway server(s) from vortex's web dashboard?

**Comment by montyanderson** [comment]
@Kalloritis Yes there is: the web ui keeps track of recent activity, while a server-side audit happens every 24 hours. The S3 traffic doesn't go through the web ui so only shows up on the audit.

**Comment by super3** [comment]
We should include a warning or info on the usage page.
